# Generated by Django 5.1.4 on 2025-09-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_students_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
